-- Demo seed data for Emergency Ambulance & Hospital Finder
-- SQLite-compatible seed script.

-- NOTE: Password values below are placeholders (bcrypt hashes). If you need working logins, replace the password strings with bcrypt hashes generated by your environment, or register via the app UI.

-- Users (Admin, Driver, Patient)
INSERT INTO users (name, email, phone, password, role) VALUES
('Admin User','admin@example.com','+10000000000','$2a$10$KIX/6H0e1Z6qK1Q6p9r1JOxQb1Y6Vf0H1Yq8e7V3aF9Q3p1z2a1bS','admin'),
('Driver One','driver1@example.com','+10000000001','$2a$10$KIX/6H0e1Z6qK1Q6p9r1JOxQb1Y6Vf0H1Yq8e7V3aF9Q3p1z2a1bS','driver'),
('Patient One','patient1@example.com','+10000000002','$2a$10$KIX/6H0e1Z6qK1Q6p9r1JOxQb1Y6Vf0H1Yq8e7V3aF9Q3p1z2a1bS','patient');

-- Hospitals
INSERT INTO hospitals (name, address, phone, latitude, longitude, emergency_available, icu_available, blood_bank_available) VALUES
('Central City Hospital','123 Main St, Central City','+10001110001',40.712776,-74.005974,1,1,1),
('Riverside Medical Center','45 River Rd, Riverside','+10001110002',40.706001,-74.008800,1,0,1),
('Lakeside General Hospital','78 Lake Ave, Lakeside','+10001110003',40.718200,-74.002600,0,1,0);

-- Ambulances (assign driver_id = 2 assuming insertion order above)
INSERT INTO ambulances (driver_id, ambulance_number, latitude, longitude, status) VALUES
(2,'AMB-1001',40.713500,-74.006000,'available'),
(2,'AMB-1002',40.709000,-74.007500,'on_duty');

-- Emergency requests (patient_id = 3)
INSERT INTO emergency_requests (patient_id, ambulance_id, hospital_id, emergency_type, latitude, longitude, status, created_at) VALUES
(3, NULL, 1, 'Accident', 40.713000, -74.006500, 'pending', datetime('now')),
(3, 1, 2, 'Medical', 40.709500, -74.007000, 'completed', datetime('now','-2 days'));

-- Emergency history entries
INSERT INTO emergency_history (request_id, changed_by, old_status, new_status, notes, created_at) VALUES
(2, 2, 'pending', 'accepted', 'Driver accepted and dispatched', datetime('now','-2 days')),
(2, 2, 'accepted', 'completed', 'Patient delivered to hospital', datetime('now','-1 day'));
